// Command extract builds testdata/regex/vim92.tsv, the table
// internal/regex is tested against.
//
// It lives under testdata so that it is not part of the build: `go build ./...`
// never sees it, `go vet ./...` never sees it, and nothing in the editor can
// accidentally depend on a tool whose only job is to interview vim once.
//
// It deliberately does not import internal/regex. The table is the oracle, and
// an oracle generated by the thing it judges is a mirror.
//
// Usage:
//
//	go run ./testdata/regex/extract [-vim /opt/homebrew/bin/vim] [-out testdata/regex/vim92.tsv]
package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"strings"
)

func main() {
	vimPath := flag.String("vim", "/opt/homebrew/bin/vim", "the vim binary to interview")
	out := flag.String("out", "testdata/regex/vim92.tsv", "the table to write")
	flag.Parse()

	if err := run(*vimPath, *out); err != nil {
		fmt.Fprintln(os.Stderr, "extract:", err)
		os.Exit(1)
	}
}

func run(vimPath, out string) error {
	version, err := vimVersion(vimPath)
	if err != nil {
		return err
	}

	sections := []section{
		{
			name:  "generated/classes",
			note:  "every character class against twelve probe characters, generated",
			pairs: classCases(),
		},
		{
			name:  "generated/atoms",
			note:  "one row per behaviour of every atom the translator handles, generated",
			pairs: atomCases,
		},
		{
			name:  "generated/refused",
			note:  "the atoms pvim refuses; vim's answer is recorded, the test asserts the error type",
			pairs: refusedCases,
		},
		{
			name:  "hand/vimrc",
			note:  "every regex in ~/.vimrc, by hand",
			pairs: vimrcCases,
		},
	}

	var all []pair
	for _, s := range sections {
		all = append(all, s.pairs...)
	}
	results, err := runVim(vimPath, all)
	if err != nil {
		return err
	}

	var b strings.Builder
	writeHeader(&b, version, sections)

	i := 0
	dropped := 0
	for _, s := range sections {
		fmt.Fprintf(&b, "# section: %s (%d rows) - %s\n", s.name, len(s.pairs), s.note)
		tag := ""
		if s.name == "generated/refused" {
			tag = "refused"
		}
		for _, p := range s.pairs {
			r := results[i]
			i++
			if r.err != "" && tag == "" {
				// A row vim itself will not run is not a row about the
				// translator. Loud, because it means a case was written wrong.
				fmt.Fprintf(os.Stderr, "extract: vim refused %q: %s\n", p.pat, r.err)
				dropped++
				continue
			}
			fmt.Fprintf(&b, "%s\t%s\t%d\t%s\t%s\n",
				escapeTSV(p.pat), escapeTSV(p.in), r.start, escapeTSV(r.match), tag)
		}
	}
	if dropped > 0 {
		return fmt.Errorf("%d cases were rejected by vim; fix them rather than shipping a table without them", dropped)
	}

	return os.WriteFile(out, []byte(b.String()), 0o644)
}

// writeHeader writes the comment block at the top of the table. It carries the
// provenance of every row, because a table of a few hundred expectations with
// no note about where they came from is a table nobody dares change.
func writeHeader(b *strings.Builder, version string, sections []section) {
	total := 0
	for _, s := range sections {
		total += len(s.pairs)
	}

	fmt.Fprintf(b, `# vim92.tsv: what vim 9.2 says every one of these patterns matches.
#
# Generated by testdata/regex/extract. Do not edit by hand; add a case to
# testdata/regex/extract/cases.go and regenerate:
#
#	go run ./testdata/regex/extract
#
# Oracle: %s
#
# Columns, tab separated, five of them:
#
#	1 pattern       the vim pattern
#	2 input         the string it was run against
#	3 match-start   byte offset of the match, -1 for no match
#	4 match-text    the text that matched, empty when there was none
#	5 tag           empty, or "refused"
#
# Tabs, newlines, carriage returns, escapes and backslashes in columns 1, 2 and
# 4 are written \t \n \r \e \\ so that every row is one line.
#
# A row tagged "refused" is a pattern vim runs and pvim will not: the test
# asserts that internal/regex returns the error type for that atom, and column 3
# and 4 record what vim did with it so that the day the atom gets an
# implementation the expectation is already written down.
#
# How the rows were sourced, and this is the part that matters when a row looks
# wrong:
#
`, version)

	for _, s := range sections {
		fmt.Fprintf(b, "#	%-20s %4d rows  %s\n", s.name, len(s.pairs), s.note)
	}

	fmt.Fprintf(b, `#	%-20s %4d rows
#
# Two sources are not here, and both are absences rather
# than omissions:
#
#   - vim's own test suite. test_regexp_latin.vim and test_regexp_utf8.vim
#     carry a few hundred triples, and neither is on this machine: the Homebrew
#     macvim 9.2.0321 formula installs the runtime files and not src/testdir,
#     /opt/homebrew/share/vim is empty, and a search of the filesystem found
#     nothing. If a vim source tree ever appears, its triples belong in a
#     section of their own here.
#
#   - the four nofrils colourscheme files. They were read and they contain no
#     regular expressions at all: 130 hi lines, four if/exists guards and two
#     function bodies that call :hi, and not one pattern between them. There is
#     nothing to extract.
#
# Two things about the oracle itself, because they decide which rows can exist:
#
#   - vim answers through match() and matchstr() over a String, where a line
#     break is an ordinary character. In a buffer it is not: there, "." and the
#     negated classes stop at the end of a line and "^" and "$" anchor to one.
#     So rows whose input contains a line break are only here when both readings
#     give the same answer, which is the \_ forms, \n and the collections. The
#     line-break behaviour of "." and of the anchors is asserted directly in
#     internal/regex's own tests instead.
#
#   - the script runs :s/x/bc/ before the first case, so "~" expands to "bc".
#     Compile the rows with Options{LastSubstitute: "bc"} and everything else
#     zero: 'ignorecase' and 'smartcase' are off and 'magic' is on, which is
#     what --clean gives and what the script sets explicitly anyway.
#
`, "total", total)
}

// vimVersion reads the first line of vim --version, which carries the patch
// level this table was built against and is the reason the file is called
// vim92 and not vim.
func vimVersion(vimPath string) (string, error) {
	out, err := exec.Command(vimPath, "--version").Output()
	if err != nil {
		return "", fmt.Errorf("%s --version: %w", vimPath, err)
	}
	lines := strings.Split(string(out), "\n")
	v := strings.TrimSpace(lines[0])
	for _, l := range lines {
		if strings.HasPrefix(l, "Included patches:") {
			v += ", " + strings.TrimSpace(l)
			break
		}
	}
	return vimPath + " - " + v, nil
}
