package window

import (
	"bufio"
	"bytes"
	"os"
	"strconv"
	"strings"
	"testing"

	"github.com/pkar/pvim/internal/options"
	"github.com/pkar/pvim/internal/text"
)

// lines returns a buffer of the lines "1" to "n", which is the corpus every
// number in this package's testdata was measured over.
func lines(n int) *text.Buffer {
	var b bytes.Buffer
	for i := 1; i <= n; i++ {
		b.WriteString(strconv.Itoa(i))
		b.WriteByte('\n')
	}
	return text.Read(b.Bytes())
}

// at returns a window on a 400-line buffer, scrolled and with the cursor
// placed, in the state vim was in when the expected numbers were read out of
// it.
func at(height, top, cursor int) *Window {
	w := New(1, lines(400), options.Defaults().GW)
	w.SetHeight(height)
	w.View.Width = 80
	w.View.TopLine = top
	w.View.Cursor = text.Pos{Line: cursor}
	return w
}

// TestHeadlessWindowIsTwentyThreeRows pins the measurement most of this file
// rests on. "vim --clean -i NONE --not-a-term -s" reports &lines 24, &columns
// 80, &window 23 and &scroll 11.
func TestHeadlessWindowIsTwentyThreeRows(t *testing.T) {
	w := at(23, 1, 1)
	if w.View.Height != 23 {
		t.Fatalf("height %d, want 23", w.View.Height)
	}
	if w.Opt.Scroll != 11 {
		t.Errorf("'scroll' starts at %d, want 11: vim reports &scroll 11 in a 23-row window", w.Opt.Scroll)
	}
	if got := w.BotLine(); got != 23 {
		t.Errorf("bottom line %d, want 23", got)
	}
}

// scrollCase is one row of testdata/window/scroll-vim9.2.0321.txt.
type scrollCase struct {
	line                       int
	keys                       string
	height, so, top, cursor    int
	wantTop, wantCur, wantScrl int
}

// readScrollTable parses the measured table. It is a fixed-column text file
// rather than a Go table because the file is generated by the shell script that
// drove vim, and a generated Go literal is a file nobody dares regenerate.
func readScrollTable(t *testing.T) []scrollCase {
	t.Helper()
	return readMeasured(t, "../../testdata/window/scroll-vim9.2.0321.txt")
}

// readMeasured parses one of the fixed-column tables under testdata/window.
// Both the scroll table and the H, M and L one have the same nine columns, so
// they have one reader.
func readMeasured(t *testing.T, path string) []scrollCase {
	t.Helper()
	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("opening %s: %v", path, err)
	}
	defer f.Close()

	var out []scrollCase
	sc := bufio.NewScanner(f)
	for n := 1; sc.Scan(); n++ {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) != 9 || fields[5] != "->" {
			t.Fatalf("%s:%d: want 9 fields with -> in the middle, got %q", path, n, line)
		}
		num := func(i int) int {
			v, err := strconv.Atoi(fields[i])
			if err != nil {
				t.Fatalf("%s:%d: field %d: %v", path, n, i, err)
			}
			return v
		}
		out = append(out, scrollCase{
			line: n, keys: fields[0],
			height: num(1), so: num(2), top: num(3), cursor: num(4),
			wantTop: num(6), wantCur: num(7), wantScrl: num(8),
		})
	}
	if err := sc.Err(); err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	if len(out) == 0 {
		t.Fatalf("%s held no cases", path)
	}
	return out
}

// runKeys applies the compact key notation the table uses: an optional count,
// then one command, repeated until the string is used up. It is a parser and
// not a lookup table so that a row added to the file needs nothing added here.
func runKeys(t *testing.T, w *Window, keys string, so int) {
	t.Helper()
	for keys != "" {
		count := 0
		for len(keys) > 0 && keys[0] >= '0' && keys[0] <= '9' {
			count = count*10 + int(keys[0]-'0')
			keys = keys[1:]
		}
		var cmd ScrollCmd
		switch {
		case strings.HasPrefix(keys, "<C-U>"):
			cmd, keys = HalfUp, keys[5:]
		case strings.HasPrefix(keys, "<C-D>"):
			cmd, keys = HalfDown, keys[5:]
		case strings.HasPrefix(keys, "<C-F>"):
			cmd, keys = PageForward, keys[5:]
		case strings.HasPrefix(keys, "<C-B>"):
			cmd, keys = PageBack, keys[5:]
		case strings.HasPrefix(keys, "<C-E>"):
			cmd, keys = LineDown, keys[5:]
		case strings.HasPrefix(keys, "<C-Y>"):
			cmd, keys = LineUp, keys[5:]
		case strings.HasPrefix(keys, "z<CR>"):
			cmd, keys = RedrawTopFirst, keys[5:]
		case strings.HasPrefix(keys, "zt"):
			cmd, keys = RedrawTop, keys[2:]
		case strings.HasPrefix(keys, "zz"):
			cmd, keys = RedrawMiddle, keys[2:]
		case strings.HasPrefix(keys, "zb"):
			cmd, keys = RedrawBottom, keys[2:]
		case strings.HasPrefix(keys, "z."):
			cmd, keys = RedrawMiddleFirst, keys[2:]
		case strings.HasPrefix(keys, "z-"):
			cmd, keys = RedrawBottomFirst, keys[2:]
		case strings.HasPrefix(keys, "z+"):
			cmd, keys = ScreenDown, keys[2:]
		case strings.HasPrefix(keys, "z^"):
			cmd, keys = ScreenUp, keys[2:]
		case strings.HasPrefix(keys, "G"):
			// A jump, not a scroll: it moves the cursor and lets
			// ScrollToCursor decide what the window does, which is the other
			// half of the same constraint.
			keys = keys[1:]
			line := count
			if line == 0 {
				line = w.Buf.LineCount()
			}
			w.View.Cursor = text.Pos{Line: line}
			w.ScrollToCursor(so)
			continue
		default:
			t.Fatalf("unknown key notation %q", keys)
		}
		w.Scroll(cmd, count, so)
	}
}

// TestScrollMatchesVim replays every row of the measured table.
//
// This is the whole point of the package. 211 of the 270 differences in the
// last fuzz run were keys that need a window, and every one of them is a row
// here: CTRL-U alone was 85 of them.
func TestScrollMatchesVim(t *testing.T) {
	for _, tc := range readScrollTable(t) {
		name := tc.keys + " h" + strconv.Itoa(tc.height) + " so" + strconv.Itoa(tc.so) +
			" from " + strconv.Itoa(tc.top) + "/" + strconv.Itoa(tc.cursor)
		t.Run(name, func(t *testing.T) {
			w := at(tc.height, tc.top, tc.cursor)
			runKeys(t, w, tc.keys, tc.so)

			if w.View.TopLine != tc.wantTop {
				t.Errorf("top line %d, vim says %d (testdata line %d)", w.View.TopLine, tc.wantTop, tc.line)
			}
			if w.View.Cursor.Line != tc.wantCur {
				t.Errorf("cursor line %d, vim says %d (testdata line %d)", w.View.Cursor.Line, tc.wantCur, tc.line)
			}
			if w.Opt.Scroll != tc.wantScrl {
				t.Errorf("'scroll' %d, vim says %d (testdata line %d)", w.Opt.Scroll, tc.wantScrl, tc.line)
			}
		})
	}
}

// TestCountChangesScrollAndItSticks is the rule behind 85 of the 270 fuzz
// failures, called out on its own because a row in a table is easy to lose.
// Measured: &scroll is 11, "5<C-U>" makes it 5, and it stays 5.
func TestCountChangesScrollAndItSticks(t *testing.T) {
	w := at(23, 100, 110)
	w.Scroll(HalfUp, 5, 3)
	if w.Opt.Scroll != 5 {
		t.Fatalf("'scroll' after 5<C-U> is %d, want 5", w.Opt.Scroll)
	}
	w.Scroll(HalfUp, 0, 3)
	if got := w.View.Cursor.Line; got != 100 {
		t.Errorf("a bare <C-U> after 5<C-U> moved to line %d, want 100: the count persisted as 'scroll'", got)
	}
}

// TestScrollReportsWhetherItMoved is what the caller turns into a beep.
func TestScrollReportsWhetherItMoved(t *testing.T) {
	for _, tc := range []struct {
		name       string
		top, cur   int
		cmd        ScrollCmd
		wantMoved  bool
		wantCursor int
	}{
		{"<C-U> on the first line", 1, 1, HalfUp, false, 1},
		{"<C-U> with the cursor below the top still walks it up", 1, 5, HalfUp, true, 1},
		{"<C-B> at the top does nothing at all", 1, 20, PageBack, false, 20},
		{"<C-Y> at the top", 1, 1, LineUp, false, 1},
		{"<C-E> at the very end", 400, 400, LineDown, false, 400},
	} {
		t.Run(tc.name, func(t *testing.T) {
			w := at(23, tc.top, tc.cur)
			if got := w.Scroll(tc.cmd, 0, 3); got != tc.wantMoved {
				t.Errorf("moved = %v, want %v", got, tc.wantMoved)
			}
			if w.View.Cursor.Line != tc.wantCursor {
				t.Errorf("cursor on line %d, want %d", w.View.Cursor.Line, tc.wantCursor)
			}
		})
	}
}

// TestLineDownReachesTheLastLine is the difference between CTRL-E and CTRL-D
// written as a test, because it is the one place two commands that look alike
// have different limits. Measured: "G" then 30 CTRL-E leaves w0 400 on a
// 400-line file, where CTRL-D stops at 378.
func TestLineDownReachesTheLastLine(t *testing.T) {
	w := at(23, 378, 400)
	w.Scroll(LineDown, 30, 3)
	if w.View.TopLine != 400 {
		t.Errorf("30<C-E> from the last screenful gave a top line of %d, vim says 400", w.View.TopLine)
	}

	w = at(23, 378, 395)
	w.Scroll(HalfDown, 0, 3)
	if w.View.TopLine != 378 {
		t.Errorf("<C-D> on the last screenful gave a top line of %d, vim says 378: it will not scroll past the end", w.View.TopLine)
	}
	if w.View.Cursor.Line != 400 {
		t.Errorf("<C-D> on the last screenful left the cursor on %d, vim says 400: it still moves the cursor", w.View.Cursor.Line)
	}
}

// TestScrollOffIsSuspendedAtTheEnds is what H and L depend on. Measured: at the
// top of the file H is line 1, not line 4; with G showing 378 to 400, L is 400
// and not 397.
func TestScrollOffIsSuspendedAtTheEnds(t *testing.T) {
	w := at(23, 1, 1)
	w.CursorInView(3)
	if w.View.Cursor.Line != 1 {
		t.Errorf("at the top of the buffer the cursor was pushed to %d; 'scrolloff' is suspended there", w.View.Cursor.Line)
	}
	if v := w.Visible(); !v.AtTop {
		t.Error("a window with TopLine 1 is not reporting AtTop")
	}

	w = at(23, 378, 400)
	w.CursorInView(3)
	if w.View.Cursor.Line != 400 {
		t.Errorf("at the end of the buffer the cursor was pulled to %d; 'scrolloff' is suspended there", w.View.Cursor.Line)
	}
	if v := w.Visible(); !v.AtBottom {
		t.Error("a window showing the last line is not reporting AtBottom")
	}

	// In the middle it is not suspended: top 100 with 'scrolloff' 3 means the
	// cursor may not go above 103, which is exactly where H lands.
	w = at(23, 100, 100)
	w.CursorInView(3)
	if w.View.Cursor.Line != 103 {
		t.Errorf("cursor on a scrolled window went to %d, want 103", w.View.Cursor.Line)
	}
}

// TestShortBuffer is the case the fuzzer hits most: a file with fewer lines
// than the window, where most scroll commands have nowhere to go.
//
// Two of them do go somewhere and the surprise is worth a test of its own.
// CTRL-F puts the last line alone at the top even when the whole four-line file
// was already showing, because its end-of-buffer branch does not ask whether
// scrolling would help. CTRL-E scrolls one line off the top for the same
// reason. Measured over a four-line file in a 23-row window at 'scrolloff' 3
// with the cursor on line 2.
func TestShortBuffer(t *testing.T) {
	for _, tc := range []struct {
		name             string
		cmd              ScrollCmd
		wantTop, wantCur int
	}{
		{"<C-U>", HalfUp, 1, 1},
		{"<C-D>", HalfDown, 1, 4},
		{"<C-B>", PageBack, 1, 2},
		{"<C-F>", PageForward, 4, 4},
		{"<C-E>", LineDown, 2, 4},
		{"<C-Y>", LineUp, 1, 2},
		{"zt", RedrawTop, 1, 2},
		{"zz", RedrawMiddle, 1, 2},
		{"zb", RedrawBottom, 1, 2},
		{"z<CR>", RedrawTopFirst, 1, 2},
		{"z+", ScreenDown, 1, 4},
		{"z^", ScreenUp, 1, 1},
	} {
		t.Run(tc.name, func(t *testing.T) {
			w := New(1, lines(4), options.Defaults().GW)
			w.SetHeight(23)
			w.View.Cursor = text.Pos{Line: 2}
			w.Scroll(tc.cmd, 0, 3)
			if w.View.TopLine != tc.wantTop {
				t.Errorf("top line %d, vim says %d", w.View.TopLine, tc.wantTop)
			}
			if w.View.Cursor.Line != tc.wantCur {
				t.Errorf("cursor line %d, vim says %d", w.View.Cursor.Line, tc.wantCur)
			}
		})
	}
}

// TestScrollOffLargerThanTheWindow pins vim's clamp. In a 5-row window
// 'scrolloff' 3 behaves as 2, so zt on line 4 gives a top line of 2 and not 1.
func TestScrollOffLargerThanTheWindow(t *testing.T) {
	w := at(5, 1, 4)
	w.Scroll(RedrawTop, 0, 3)
	if w.View.TopLine != 2 {
		t.Errorf("zt in a 5-row window at 'scrolloff' 3 gave a top line of %d, vim says 2", w.View.TopLine)
	}
}

// TestSetHeightRecomputesScroll: vim's 'scroll' follows the window height, so a
// window dragged taller moves further on the next CTRL-D with no count typed.
func TestSetHeightRecomputesScroll(t *testing.T) {
	w := at(23, 1, 1)
	w.SetHeight(41)
	if w.Opt.Scroll != 20 {
		t.Errorf("'scroll' in a 41-row window is %d, want 20", w.Opt.Scroll)
	}
}

// TestFirstNonBlank is what separates z<CR> from zt.
func TestFirstNonBlank(t *testing.T) {
	b := text.Read([]byte("no indent\n\t  indented\n\n"))
	w := New(1, b, options.Defaults().GW)
	w.SetHeight(23)

	for _, tc := range []struct {
		line, want int
	}{
		{1, 0},
		{2, 3},
		{3, 0}, // an empty line has no non-blank and stays in column 0
	} {
		w.View.Cursor = text.Pos{Line: tc.line, Col: 0}
		w.FirstNonBlank()
		if w.View.Cursor.Col != tc.want {
			t.Errorf("line %d: first non-blank at column %d, want %d", tc.line, w.View.Cursor.Col, tc.want)
		}
	}
}

// TestRedrawStopsAtTheLastScreenful is the bottom 'scrolloff' push held to the
// lines that exist.
//
// Vim's update_topline runs its bottom check only while w_botline is still
// inside the buffer, and scroll_cursor_bot stops counting 'scrolloff' context
// the moment it walks off the end, so zb never scrolls further than the last
// screenful. Measured over a 39-row window at 'scrolloff' 5, where "Gzb" lands
// on max(1, lines-38) for every file size: an uncapped push landed five lines
// lower every time, and on a 38-line file it scrolled a buffer that fits in
// the window to a top line of 5.
func TestRedrawStopsAtTheLastScreenful(t *testing.T) {
	for _, tc := range []struct {
		lines, wantTop int
	}{
		{38, 1},
		{39, 1},
		{40, 2},
		{41, 3},
		{45, 7},
		{400, 362},
	} {
		w := New(1, lines(tc.lines), options.Defaults().GW)
		w.SetHeight(39)
		w.View.Width = 80
		w.View.Cursor = text.Pos{Line: tc.lines}
		w.ScrollToCursor(5)
		w.Scroll(RedrawBottom, 0, 5)
		if w.View.TopLine != tc.wantTop {
			t.Errorf("Gzb on a %d-line file in a 39-row window gave a top line of %d, vim says %d",
				tc.lines, w.View.TopLine, tc.wantTop)
		}
	}

	// The same rule one cursor line at a time, which is where it is easiest to
	// see: at 'scrolloff' 3 in a 23-row window the last four lines of a
	// 400-line file all answer 378, because the push has nothing left to ask
	// for. Line 397 is the last one whose margin fits.
	for _, tc := range []struct{ cursor, wantTop int }{
		{396, 377}, {397, 378}, {398, 378}, {399, 378}, {400, 378},
	} {
		w := at(23, 1, 1)
		w.View.Cursor = text.Pos{Line: tc.cursor}
		w.ScrollToCursor(3)
		w.Scroll(RedrawBottom, 0, 3)
		if w.View.TopLine != tc.wantTop {
			t.Errorf("zb with the cursor on %d gave a top line of %d, vim says %d",
				tc.cursor, w.View.TopLine, tc.wantTop)
		}
	}
}

// TestHalfDownWillNotScrollBackwards is CTRL-D on a window zt, zz or CTRL-E has
// already pushed past the last screenful.
//
// Vim's halfpage() advances the top one line at a time while w_botline is still
// inside the buffer, so it stops rather than reversing. A clamp to the last
// screenful is a backwards scroll here, and it moved the top 33 lines the wrong
// way. The cursor still walks its full 'scroll', which is what makes the two
// halves of the command different.
func TestHalfDownWillNotScrollBackwards(t *testing.T) {
	for _, tc := range []struct {
		name             string
		setup            func(*Window)
		wantTop, wantCur int
	}{
		{"Gzt", func(w *Window) {
			w.View.Cursor = text.Pos{Line: 400}
			w.ScrollToCursor(5)
			w.Scroll(RedrawTop, 0, 5)
		}, 395, 400},
		{"380Gzt", func(w *Window) {
			w.View.Cursor = text.Pos{Line: 380}
			w.ScrollToCursor(5)
			w.Scroll(RedrawTop, 0, 5)
		}, 375, 399},
		{"G then five CTRL-E", func(w *Window) {
			w.View.Cursor = text.Pos{Line: 400}
			w.ScrollToCursor(5)
			w.Scroll(LineDown, 5, 5)
		}, 367, 400},
	} {
		t.Run(tc.name, func(t *testing.T) {
			w := New(1, lines(400), options.Defaults().GW)
			w.SetHeight(39)
			w.View.Width = 80
			tc.setup(w)
			w.Scroll(HalfDown, 0, 5)
			if w.View.TopLine != tc.wantTop {
				t.Errorf("top line %d after CTRL-D, vim says %d", w.View.TopLine, tc.wantTop)
			}
			if w.View.Cursor.Line != tc.wantCur {
				t.Errorf("cursor line %d after CTRL-D, vim says %d", w.View.Cursor.Line, tc.wantCur)
			}
		})
	}
}

// TestPageBackPastTheLastScreenful is CTRL-B from a window showing one buffer
// line above a screen of tildes.
//
// The line that lands on the bottom row is the one below the old top, and it
// may not be the last line of the file, so the jump is longer than the window
// less two. Measured on a 50-line file in a 39-row window at 'scrolloff' 5:
// three CTRL-Fs leave the top on 50, and the CTRL-B after them gives a top of
// 11 showing to 49 with the cursor on 44, where the (h-2) arithmetic gave 13,
// showed to 50 and left the cursor on 45. That one row is what made the H, M
// and L after it land on 16, 31 and 50 instead of 16, 30 and 44.
func TestPageBackPastTheLastScreenful(t *testing.T) {
	w := New(1, lines(50), options.Defaults().GW)
	w.SetHeight(39)
	w.View.Width = 80
	for i := 0; i < 3; i++ {
		w.Scroll(PageForward, 0, 5)
	}
	if w.View.TopLine != 50 || w.View.Cursor.Line != 50 {
		t.Fatalf("three CTRL-Fs left top %d cursor %d, vim says 50 and 50",
			w.View.TopLine, w.View.Cursor.Line)
	}
	w.Scroll(PageBack, 0, 5)
	if w.View.TopLine != 11 {
		t.Errorf("top line %d after CTRL-B, vim says 11", w.View.TopLine)
	}
	if got := w.BotLine(); got != 49 {
		t.Errorf("bottom line %d after CTRL-B, vim says 49", got)
	}
	if w.View.Cursor.Line != 44 {
		t.Errorf("cursor line %d after CTRL-B, vim says 44", w.View.Cursor.Line)
	}
}

// TestScreenCountIsALineNumber is z+ and z^ with a count, which is not a repeat.
//
// ":help z+" says a count makes it "just like z<CR>". ":help z^" says a count
// scrolls line [count] to the bottom and then does the bare z^ on the window
// that leaves, which is vim's nv_zet doing scroll_cursor_bot twice with the
// cursor moved to the resulting top line in between. Measured in a 23-row
// window over a 400-line file from top 100 with the cursor on 110.
func TestScreenCountIsALineNumber(t *testing.T) {
	for _, tc := range []struct {
		name             string
		cmd              ScrollCmd
		count, so        int
		wantTop, wantCur int
	}{
		{"2z+", ScreenDown, 2, 0, 2, 2},
		{"50z+", ScreenDown, 50, 0, 50, 50},
		{"100z+", ScreenDown, 100, 0, 100, 100},
		{"50z+ at 'scrolloff' 3", ScreenDown, 50, 3, 47, 50},
		{"2z^", ScreenUp, 2, 0, 1, 1},
		{"50z^", ScreenUp, 50, 0, 6, 28},
		{"100z^", ScreenUp, 100, 0, 56, 78},
		{"50z^ at 'scrolloff' 3", ScreenUp, 50, 3, 12, 31},
		{"100z^ at 'scrolloff' 3", ScreenUp, 100, 3, 62, 81},
		// The countless forms, so that delegating them through redraw cannot
		// quietly change what they were measured to do.
		{"z+", ScreenDown, 0, 0, 123, 123},
		{"z^", ScreenUp, 0, 0, 77, 99},
		{"z+ at 'scrolloff' 3", ScreenDown, 0, 3, 120, 123},
		{"z^ at 'scrolloff' 3", ScreenUp, 0, 3, 80, 99},
	} {
		t.Run(tc.name, func(t *testing.T) {
			w := at(23, 100, 110)
			w.Scroll(tc.cmd, tc.count, tc.so)
			if w.View.TopLine != tc.wantTop {
				t.Errorf("top line %d, vim says %d", w.View.TopLine, tc.wantTop)
			}
			if w.View.Cursor.Line != tc.wantCur {
				t.Errorf("cursor line %d, vim says %d", w.View.Cursor.Line, tc.wantCur)
			}
		})
	}
}
